export const ORG_ROLES = [
  'owner',
  'it_manager',
  'service_desk_manager',
  'analyst',
  'desktop_engineer',
  'infrastructure_engineer',
  'security_analyst',
  'auditor',
  'end_user',
] as const

export type OrgRole = (typeof ORG_ROLES)[number]

export const PERMISSIONS = [
  'tenant.read',
  'tenant.manage',
  'member.read',
  'member.manage',
  'ticket.read',
  'ticket.write',
  'ticket.assign',
  'ticket.resolve',
  'device.read',
  'device.manage',
  'monitoring.read',
  'monitoring.manage',
  'device.restart',
  'remote.attended',
  'remote.unattended',
  'remote.inspection',
  'remote.control',
  'remote.elevated',
  'script.read',
  'script.execute',
  'script.manage',
  'kb.read',
  'kb.write',
  'automation.read',
  'automation.manage',
  'asset.read',
  'asset.manage',
  'catalogue.read',
  'catalogue.manage',
  'canned.read',
  'canned.manage',
  'entra.read',
  'entra.manage',
  'ad.read',
  'ad.manage',
  'ai.use',
  'ai_agent.read',
  'ai_agent.manage',
  'chat.read',
  'chat.write',
  'telephony.read',
  'telephony.manage',
  'incident.read',
  'incident.manage',
  'grant.request',
  'grant.read',
  'grant.approve',
  'patch.read',
  'patch.manage',
  'patch.approve',
  'integration.read',
  'integration.manage',
  'rmm.read',
  'rmm.manage',
  'report.read',
  'audit.read',
  'notification.read',
  'settings.manage',
  'billing.manage',
] as const

export type Permission = (typeof PERMISSIONS)[number]

const ALL: readonly Permission[] = PERMISSIONS

const TECH_BASE: readonly Permission[] = [
  'tenant.read',
  'member.read',
  'ticket.read',
  'ticket.write',
  'ticket.assign',
  'ticket.resolve',
  'canned.read',
  'device.read',
  'monitoring.read',
  'kb.read',
  'asset.read',
  'catalogue.read',
  'entra.read',
  'ad.read',
  'ai.use',
  'ai_agent.read',
  'chat.read',
  'chat.write',
  'telephony.read',
  'incident.read',
  'grant.request',
  'grant.read',
  'patch.read',
  'rmm.read',
  'notification.read',
  'report.read',
]

const REMOTE_WORKSTATION: readonly Permission[] = [
  'remote.attended',
  'remote.unattended',
  'remote.inspection',
  'remote.control',
  'device.restart',
  'script.read',
  'script.execute',
]

export const ROLE_PERMISSIONS: Record<OrgRole, readonly Permission[]> = {
  owner: ALL,
  it_manager: ALL.filter((p) => p !== 'billing.manage'),
  service_desk_manager: [
    ...TECH_BASE,
    'canned.manage',
    'kb.write',
    'remote.attended',
    'remote.unattended',
    'remote.inspection',
    'settings.manage',
    'member.manage',
    'automation.read',
    'automation.manage',
    'asset.read',
    'asset.manage',
    'catalogue.read',
    'catalogue.manage',
    'entra.read',
    'entra.manage',
    'ad.read',
    'ad.manage',
    'telephony.read',
    'telephony.manage',
    'incident.manage',
    'grant.approve',
    'patch.read',
    'patch.manage',
    'patch.approve',
    'integration.read',
    'integration.manage',
    'rmm.read',
    'rmm.manage',
    'ai_agent.manage',
    'script.read',
    'script.manage',
    'audit.read',
  ],
  analyst: [
    ...TECH_BASE,
    'remote.attended',
    'remote.inspection',
  ],
  desktop_engineer: [...TECH_BASE, ...REMOTE_WORKSTATION],
  infrastructure_engineer: [
    ...TECH_BASE,
    'monitoring.manage',
    ...REMOTE_WORKSTATION,
    'remote.elevated',
    'device.manage',
    'asset.manage',
    'script.manage',
    'ad.read',
    'ad.manage',
    'telephony.read',
    'telephony.manage',
    'incident.manage',
    'patch.read',
    'patch.manage',
    'rmm.read',
    'rmm.manage',
    'ai_agent.manage',
  ],
  security_analyst: [
    'tenant.read',
    'member.read',
    'ticket.read',
    'device.read',
    'remote.inspection',
    'kb.read',
    'entra.read',
    'ad.read',
    'chat.read',
    'telephony.read',
    'incident.read',
    'grant.read',
    'patch.read',
    'integration.read',
    'rmm.read',
    'ai_agent.read',
    'notification.read',
    'report.read',
    'audit.read',
  ],
  auditor: [
    'tenant.read',
    'member.read',
    'ticket.read',
    'device.read',
    'kb.read',
    'ad.read',
    'chat.read',
    'telephony.read',
    'incident.read',
    'grant.read',
    'patch.read',
    'integration.read',
    'rmm.read',
    'ai_agent.read',
    'notification.read',
    'report.read',
    'audit.read',
  ],
  end_user: ['notification.read'],
}

export function isOrgRole(value: string): value is OrgRole {
  return (ORG_ROLES as readonly string[]).includes(value)
}

export function permissionsForRole(role: OrgRole): readonly Permission[] {
  return ROLE_PERMISSIONS[role] ?? []
}

export function roleHasPermission(role: OrgRole, permission: Permission): boolean {
  return permissionsForRole(role).includes(permission)
}

export function roleHasAll(role: OrgRole, permissions: readonly Permission[]): boolean {
  const granted = new Set<Permission>(permissionsForRole(role))
  return permissions.every((p) => granted.has(p))
}
