import type { BillingConfig } from '../../config.js'

/**
 * Payment-gateway abstraction. Tenants are routed to a provider by their
 * billing country (Paystack for supported African countries, Stripe for the
 * rest), with a manual/offline fallback available everywhere.
 */
export type GatewaySlug = 'paystack' | 'stripe' | 'manual'

export type GatewayMethod =
  | 'card'
  | 'bank_transfer'
  | 'ussd'
  | 'mobile_money'
  | 'apple_pay'
  | 'google_pay'
  | 'manual'

export interface GatewayMethodInfo {
  id: GatewayMethod
  label: string
  description: string
  /** Optional small print, e.g. "Nigeria only" for USSD. */
  note?: string
}

export interface GatewayInfo {
  slug: GatewaySlug
  label: string
  enabled: boolean
  methods: GatewayMethodInfo[]
}

export interface CheckoutInput {
  tenantId: string
  tenantName: string
  email: string
  planSlug: string
  planName: string
  /** Price in local currency cents (already converted). */
  amountCents: number
  currency: string
  billingCycle: 'monthly' | 'annual'
  country: string
  /** Tenant-unique reference, generated by the service layer. */
  reference: string
  callbackUrl: string
}

export interface CheckoutResult {
  url: string
  /** Provider-side checkout id (Stripe session id / Paystack reference). */
  checkoutId?: string
  /** Provider-side entity id (subscription id) when known immediately. */
  subscriptionId?: string
  customerId?: string
}

export interface VerifyResult {
  paid: boolean
  subscriptionId?: string
  customerId?: string
  /** Payment method details collected from the provider (cards/authorizations). */
  method?: {
    gatewayMethod: Exclude<GatewayMethod, 'manual'>
    brand: string
    last4: string
    expMonth?: number
    expYear?: number
    externalId: string
    authData?: Record<string, unknown>
  }
}

export type WebhookEvent =
  | { type: 'charge.success'; reference: string; verify: VerifyResult }
  | { type: 'subscription.disable'; subscriptionId: string; reason: string }
  | { type: 'subscription.payment_failed'; subscriptionId: string; invoiceReference?: string }
  | { type: 'unknown'; raw: string }

export interface PaymentGateway {
  slug: GatewaySlug
  label: string
  enabled: boolean
  methods(country?: string): GatewayMethodInfo[]
  createCheckout(input: CheckoutInput): Promise<CheckoutResult>
  verify(reference: string): Promise<VerifyResult>
  /** Validate provider signature and map to a normalized WebhookEvent. */
  handleWebhook(rawBody: string, signature: string): WebhookEvent | null
  cancelSubscription(subscriptionId: string): Promise<void>
}

/** Countries where Paystack operates with local payment methods. */
export const PAYSTACK_COUNTRIES = new Set([
  'NG', 'GH', 'KE', 'ZA', 'EG', 'CI', 'RW', 'UG', 'TZ',
])

const PAYSTACK_METHODS: GatewayMethodInfo[] = [
  { id: 'card', label: 'Card', description: 'Debit or credit card (Visa, Mastercard, Verve).' },
  { id: 'bank_transfer', label: 'Bank transfer', description: 'Pay via instant bank transfer — no card needed.' },
  { id: 'ussd', label: 'USSD', description: 'Pay with any phone using a USSD code.', note: 'Nigeria' },
  { id: 'mobile_money', label: 'Mobile money', description: 'M-Pesa, MoMo and other mobile wallets.', note: 'Kenya, Tanzania, Ghana, Rwanda, Uganda' },
  { id: 'apple_pay', label: 'Apple Pay', description: 'Fast checkout on iOS and Safari.' },
  { id: 'google_pay', label: 'Google Pay', description: 'Fast checkout on Android and Chrome.' },
]

const STRIPE_METHODS: GatewayMethodInfo[] = [
  { id: 'card', label: 'Card', description: 'Visa, Mastercard, Amex and debit cards.' },
  { id: 'apple_pay', label: 'Apple Pay', description: 'Fast checkout on iOS and Safari.' },
  { id: 'google_pay', label: 'Google Pay', description: 'Fast checkout on Android and Chrome.' },
]

const MANUAL_METHODS: GatewayMethodInfo[] = [
  { id: 'manual', label: 'Pay by invoice (offline)', description: 'We send an invoice; pay by bank transfer. Ideal for enterprise.' },
]

/** Approximate USD → local currency conversion (minor units denominator is 100). */
export const FX_RATES: Record<string, number> = {
  USD: 1,
  NGN: 1500,
  GHS: 15,
  KES: 130,
  ZAR: 18,
  EGP: 48,
  XOF: 600,
  UGX: 3700,
  RWF: 1300,
  TZS: 2600,
}

export function currencyForCountry(country: string): string {
  const map: Record<string, string> = {
    NG: 'NGN', GH: 'GHS', KE: 'KES', ZA: 'ZAR', EG: 'EGP',
    CI: 'XOF', RW: 'RWF', UG: 'UGX', TZ: 'TZS', US: 'USD', GB: 'GBP',
  }
  return map[country.toUpperCase()] ?? 'USD'
}

export function convertUsdCents(usdCents: number, country: string): { amountCents: number; currency: string } {
  const currency = currencyForCountry(country)
  const rate = FX_RATES[currency] ?? 1
  return { amountCents: Math.max(1, Math.round(usdCents * rate)), currency }
}

export function gatewayForCountry(country: string, config: BillingConfig): GatewaySlug {
  const upper = country.toUpperCase()
  if (PAYSTACK_COUNTRIES.has(upper) && config.paystackSecretKey) return 'paystack'
  if (config.stripeSecretKey) return 'stripe'
  return 'manual'
}

export function availableGateways(country: string, config: BillingConfig): GatewayInfo[] {
  const gateways: GatewayInfo[] = []
  if (config.paystackSecretKey && PAYSTACK_COUNTRIES.has(country.toUpperCase())) {
    gateways.push({ slug: 'paystack', label: 'Paystack', enabled: true, methods: PAYSTACK_METHODS })
  }
  if (config.stripeSecretKey) {
    gateways.push({ slug: 'stripe', label: 'Stripe', enabled: true, methods: STRIPE_METHODS })
  }
  gateways.push({ slug: 'manual', label: 'Offline/invoice', enabled: true, methods: MANUAL_METHODS })
  return gateways
}

export function countryOptions(): Array<{ code: string; name: string; gateway: GatewaySlug }> {
  const countries = [
    ['NG', 'Nigeria'], ['GH', 'Ghana'], ['KE', 'Kenya'], ['ZA', 'South Africa'],
    ['EG', 'Egypt'], ['CI', 'Côte d’Ivoire'], ['RW', 'Rwanda'], ['UG', 'Uganda'],
    ['TZ', 'Tanzania'], ['US', 'United States'], ['GB', 'United Kingdom'], ['CA', 'Canada'],
    ['DE', 'Germany'], ['FR', 'France'], ['NL', 'Netherlands'], ['AE', 'UAE'],
    ['IN', 'India'], ['BR', 'Brazil'],
  ] as const
  return countries.map(([code, name]) => ({
    code,
    name,
    gateway: (PAYSTACK_COUNTRIES.has(code) ? 'paystack' : 'stripe') as GatewaySlug,
  }))
}

export { PAYSTACK_METHODS, STRIPE_METHODS, MANUAL_METHODS }

export type GatewayMap = Record<GatewaySlug, PaymentGateway>