import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, BrandRow } from '../components/ui.js'

interface EnrolInfo {
  valid: boolean
  expiresAt?: string
  helperAvailable?: boolean
  platform?: string
}

function platformLabel(platform: string): string {
  if (platform === 'macos') return 'macOS'
  if (platform === 'android') return 'Android'
  if (platform === 'windows') return 'Windows'
  return 'your device'
}

export default function EnrollPage() {
  const navigate = useNavigate()
  const { code: routeCode = '' } = useParams<{ code: string }>()
  const [entryCode, setEntryCode] = useState(routeCode)
  const code = routeCode || entryCode.replace(/\D/g, '').slice(0, 12)
  const [info, setInfo] = useState<EnrolInfo | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      setError('The code could not be copied. Select it and copy it manually.')
    }
  }

  useEffect(() => {
    if (!routeCode) return
    if (!/^\d{12}$/.test(code)) {
      setError('This enrollment code is invalid. Ask your technician for a new code.')
      return
    }
    let cancelled = false
    void fetch(`/api/enrol/${encodeURIComponent(code)}`)
      .then(async (response) => {
        if (!response.ok) {
          const payload = await response.json().catch(() => null) as { error?: { message?: string } } | null
          throw new Error(payload?.error?.message ?? 'This enrollment code is invalid or expired. Ask your technician for a new code.')
        }
        return response.json() as Promise<EnrolInfo>
      })
      .then((next) => { if (!cancelled) setInfo(next) })
      .catch((err: unknown) => { if (!cancelled) setError(err instanceof Error ? err.message : 'Could not validate this enrollment code.') })
    return () => { cancelled = true }
  }, [code, routeCode])

  const submitCode = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const normalized = entryCode.replace(/\D/g, '')
    if (normalized.length !== 12) {
      setError('Enter the 12-digit enrollment code from your technician.')
      return
    }
    navigate(`/enrol/${normalized}`)
  }

  if (!routeCode) {
    return (
      <div className="auth-screen">
        <div className="auth-panel connect-panel enrol-page">
          <BrandRow />
          <span className="settings-eyebrow">Device enrollment</span>
          <h1 className="auth-title">Enter your enrollment code</h1>
          <p className="auth-sub">Use the 12-digit code generated by your technician under Devices → Deploy / enrol.</p>
          {error ? <Alert kind="error">{error}</Alert> : null}
          <form className="connect-entry-form" onSubmit={submitCode}>
            <label className="field">
              <span className="field-label">Enrollment code</span>
              <input className="field-input connect-entry-input" value={entryCode} onChange={(event) => setEntryCode(event.target.value.replace(/\D/g, '').slice(0, 12))} inputMode="numeric" pattern="[0-9]{12}" maxLength={12} placeholder="000 000 000 000" autoComplete="one-time-code" autoFocus required />
              <span className="field-hint">12 digits · single-use · expires automatically</span>
            </label>
            <button className="btn btn-primary btn-block" type="submit">Continue to enrollment</button>
          </form>
        </div>
      </div>
    )
  }

  const platform = info?.platform ?? 'windows'
  const downloadUrl = `/api/enrol/${encodeURIComponent(code)}/download`

  const downloadAgent = async () => {
    setDownloading(true)
    setError(null)
    try {
      const response = await fetch(downloadUrl)
      const contentType = response.headers.get('content-type') ?? ''
      const looksLikeJson = contentType.toLowerCase().includes('application/json')
      if (!response.ok) {
        let message = 'The agent package could not be downloaded.'
        try {
          const payload = await response.json() as { error?: { message?: string }; message?: string }
          message = payload.error?.message ?? payload.message ?? message
        } catch {
          const text = await response.text().catch(() => '')
          if (text) message = text.slice(0, 240)
        }
        throw new Error(message)
      }
      if (looksLikeJson) {
        const payload = await response.json() as { file?: string; filename?: string; contentType?: string; error?: { message?: string } }
        if (!payload.file) throw new Error(payload.error?.message ?? 'The agent package could not be downloaded.')
        const link = document.createElement('a')
        link.href = `data:${payload.contentType ?? 'application/octet-stream'};base64,${payload.file}`
        link.download = payload.filename ?? 'reydesk-helper.exe'
        document.body.appendChild(link)
        link.click()
        link.remove()
        return
      }
      const blob = await response.blob()
      if (!blob.size) throw new Error('The downloaded agent package was empty.')
      const link = document.createElement('a')
      link.href = URL.createObjectURL(blob)
      link.download = response.headers.get('content-disposition')?.match(/filename="?([^";]+)"?/i)?.[1] ?? 'reydesk-helper.exe'
      document.body.appendChild(link)
      link.click()
      link.remove()
      URL.revokeObjectURL(link.href)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'The agent package could not be downloaded.')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="auth-screen">
      <div className="auth-panel connect-panel enrol-page">
        <BrandRow />
        <span className="settings-eyebrow">Device enrollment</span>
        <h1 className="auth-title">Add this device to ReyDesk</h1>
        <p className="auth-sub">This is an enrollment link, not a remote support session. Install the agent, enter the code, and your technician will see the device in Devices.</p>
        {error ? <Alert kind="error">{error}</Alert> : null}
        {info ? <div className="connect-request">
          <div className="connect-code"><span className="etch">Enrollment code</span><div className="support-code-digits">{code}</div><button type="button" className="btn btn-ghost btn-sm" onClick={() => void copyCode()}>{copied ? 'Copied' : 'Copy code'}</button></div>
          <section className="connect-how-to">
            <span className="settings-eyebrow">Install steps</span>
            <ol>
              <li>Download the ReyDesk agent for {platformLabel(platform)}.</li>
              <li>Run or install it on this device.</li>
              <li>Enter the 12-digit enrollment code shown above.</li>
              <li>Approve the requested Windows security or screen permissions.</li>
            </ol>
          </section>
          {info.helperAvailable ? <button type="button" className="btn btn-primary btn-block" onClick={() => void downloadAgent()} disabled={downloading}>{downloading ? 'Preparing download…' : `Download the ${platformLabel(platform)} ReyDesk agent`}</button> : <div className="connect-download"><strong>Agent download unavailable</strong><span className="muted">Ask your technician to configure the signed agent package before enrolling this device.</span></div>}
          {info.expiresAt ? <span className="muted">This code expires {new Date(info.expiresAt).toLocaleString()} and can be used once.</span> : null}
          <div className="enrol-modal-note"><strong>Important:</strong><span>Do not enter this enrollment code on the Remote Session support page. Remote Session codes and enrollment codes are separate.</span></div>
        </div> : null}
      </div>
    </div>
  )
}
